// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go an.example

package main

#Config: {
	vals: [...#Val] @go(Vals,[]Val)
	level: int @go(Level)
}

#Val: {
	name:  string @go(Name)
	value: string @go(Value)
}
